<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Pesquisar usuários
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["users/new", "Adicionar"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "users/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldId" class="col-sm-2 control-label">Id</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["id", "type" => "number", "class" => "form-control", "id" => "fieldId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNickName" class="col-sm-2 control-label">Nickname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nick_name", "size" => 30, "class" => "form-control", "id" => "fieldNickName"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php // echo $this->tag->submitButton(["Pesquisar", "class" => "btn btn-default"]) ?>
        <button class='btn btn-default'>
            <i class="fa fa-search"></i> Pesquisar
        </button>
        <?php // echo new BootstrapButton('name', ['class' => 'btn btn-default'], 'glyphicon glyphicon-asterisk'); ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
