<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["users", "Voltar"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Adicionar Usuário
    </h1>
</div>

<?php // echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Users/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Nome</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldNickName" class="col-sm-2 control-label">Nickname</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["nick_name", "size" => 30, "class" => "form-control", "id" => "fieldNickName"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Salvar", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
