<div class="container-fluid p-0">

   <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="about">
      <div class="w-100">
      <h1 class="mb-0">Gabriel
         <span class="text-primary">Braga</span>
      </h1>
      <div class="subheading mb-5">Rua Lago Verde · Inhaúma, Rio de Janeiro · (21) 99848-7930 ·
         <a href="mailto:name@email.com">m.gabriel.sb@gmail.com</a>
      </div>
      <p class="lead mb-5">Eu tenho experiência com várias linguagens de backend e frontend. Prática ágeis, TDD e ORM em diversos frameworks. Penso que colaboração com o time é fundamental para bons resultados.</p>
      <div class="social-icons">
         <a href="https://www.linkedin.com/in/gabriel-braga-b8829b159/" target="_blank">
            <i class="fab fa-linkedin-in"></i>
         </a>
         <a href="https://github.com/gbraga" target="_blank">
            <i class="fab fa-github"></i>
         </a>
         <a href="https://twitter.com/" target="_blank">
            <i class="fab fa-twitter"></i>
         </a>
         <a href="https://www.facebook.com/GabrielSouzaBraga" target="_blank">
            <i class="fab fa-facebook-f"></i>
         </a>
      </div>
      </div>
   </section>

</div>