<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="education">
    <div class="w-100">
    <h2 class="mb-5">Educação</h2>

    <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
        <div class="resume-content">
            <h3 class="mb-0">Bacharelado em Sistemas de Informação</h3>
            <div class="subheading mb-3">Universidade Estácio de Sá</div>
            <!-- <div></div> -->
            <!-- <p>GPA: 3.23</p> -->
        </div>
        <div class="resume-date text-md-right">
            <span class="text-primary">Julho 2016 - Dezembro 2018</span>
        </div>
    </div>

    <div class="resume-item d-flex flex-column flex-md-row justify-content-between">
        <div class="resume-content">
            <h3 class="mb-0">Bacharelado em Sistemas de Informação</h3>
            <div class="subheading mb-3">PUC-Rio</div>
            <p>Não concluída</p>
        </div>
        <div class="resume-date text-md-right">
            <span class="text-primary">Julho 2009 - Dezembro 2013</span>
        </div>
    </div>

    </div>
</section>