<section class="resume-section p-3 p-lg-5 d-flex justify-content-center" id="experience">
    <div class="w-100">
        <h2 class="mb-5">Experiência</h2>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Desenvolvedor</h3>
                <div class="subheading mb-3">Sofacoding</div>
                <p>
                    Responsável por projeto. Programação frontend e backend com Ionic3 e Cakephp3. 
                    Modelagem de dados e análise de requisitos, implementação do design.
                </p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">Junho 2018 - Dezembro 2018</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Desenvolvedor</h3>
                <div class="subheading mb-3">Stone Age</div>
                <p>
                    Atuei na manutenção de diversos softwares de análise de riscos e participei da concepção de diversas
                    novas ferramentas do novo portifólio da empresa, incluindo mineração de dados, monitoramento de
                    ambiente, web services, testes de softwares integrados com Jenkins, produtos selados e sistemas
                    internos do Delphi7 ao .NET.
                </p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">Março 2012 - Maio 2016</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between mb-5">
            <div class="resume-content">
                <h3 class="mb-0">Analista</h3>
                <div class="subheading mb-3">Empresa Júnior PUC-Rio</div>
                <p>
                    Cofundador do departamento de que ainda era inexistente na empresa. Prestamos serviços de sites
                    para pequenos empreendedores que desejavam se mostrar para o público digital. Trabalhamos em
                    conjunto com designers e publicitários para prestar um serviço diferenciado com identidade visual e
                    presença atuante em redes sociais.    
                </p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">Janeiro de 2011 - Julho 2011</span>
            </div>
        </div>

        <div class="resume-item d-flex flex-column flex-md-row justify-content-between">
            <div class="resume-content">
                <h3 class="mb-0">Estagiário programador</h3>
                <div class="subheading mb-3">NIT Soluções</div>
                <p>
                    Responsável direto por alguns clientes. Programação de sites institucionais e sistemas internos
                    utilizando o framework proprietário (PHP).
                </p>
            </div>
            <div class="resume-date text-md-right">
                <span class="text-primary">Janeiro 2010 - Dezembro 2010</span>
            </div>
        </div>

    </div>

</section>