<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="interests">
    <div class="w-100">
        <h2 class="mb-5">Interesses</h2>
        <p>
            Quando não estou trabalhando minhas habilidades como desenvolvedor e analista, eu constumo usar meu tempo em leituras (sci-fi e fantasy principalemente), assistir séries e ir ao cinema.    
        </p>
        <p class="mb-0">
            E quando encontro meu grupo social, costumamos jogar cartas, ir a piscina e a praia. Tento também manter uma rotina de exercícios e alongamento para combater os danos que o tempo trás e a mente sempre arejada.
        </p>
    </div>
</section>