<section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="skills">
    <div class="w-100">
    <h2 class="mb-5">Habilidades</h2>

    <div class="subheading mb-3">Linguagens &amp; Ferramentas</div>
    <ul class="list-inline dev-icons">
        <li class="list-inline-item">
            <i class="fab fa-html5"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-css3-alt"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-js-square"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-angular"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-git"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-bitbucket"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-sass"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-less"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-wordpress"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-php"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-java"></i>
        </li>
        <li class="list-inline-item">
            <i class="fab fa-npm"></i>
        </li>
    </ul>

    <div class="subheading mb-3">Workflow</div>
        <ul class="fa-ul mb-0">
            <li>
                <i class="fa-li fa fa-check"></i>
                Mobile-First, Responsive Design
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Cross Browser Testing &amp; Debugging
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Cross Functional Teams
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Agile Development &amp; Scrum
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                Code-First &amp; TDD
            </li>
            <li>
                <i class="fa-li fa fa-check"></i>
                RESTful &amp; SaaS
            </li>
        </ul>
    </div>
</section>