<?php 
    use Phalcon\Tag as Tag;
?> 
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Phalcon PHP</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>

        <!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">

        <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">

        <?php $this->assets->outputCss(); ?>
    </head>
    <body>
        <div class="container">

            <!-- particles.js container -->
            
            <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
                <div id="particles-js"></div>
                
                <a class="navbar-brand js-scroll-trigger" href="#page-top">
                    <span class="d-block d-lg-none">Gabriel Braga</span>
                    <span class="d-none d-lg-block">
                        <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="/img/profile.jpg" alt="">
                    </span>
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["/", "Sobre", "class" => "nav-link"]) ?>
                        </li>

                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["home/experience", "Experiência", "class" => "nav-link"]) ?>
                        </li>
                        
                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["home/education", "Educação", "class" => "nav-link"]) ?>
                        </li>
                        
                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["home/skills", "Habilidades", "class" => "nav-link"]) ?>
                        </li>
                        
                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["home/interests", "Interesses", "class" => "nav-link"]) ?>
                        </li>

                        <li class="nav-item">
                            <?php echo $this->tag->linkTo(["/users", "Usuários", "class" => "nav-link"]) ?>
                        </li>
                    </ul>

                </div>
            </nav>

            <?php echo $this->getContent(); ?>
        </div>
        <!-- jQuery first, then Popper.js, and then Bootstrap's JavaScript -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        <?php $this->assets->outputJs(); ?>
    </body>
</html>
